[package]
name = "zerocal"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
axum = "0.5"
chrono = "0.4.22"
dateparser = "0.1.7"
humantime = "2.1.0"
icalendar = "0.13.1"
shuttle-service = { version = "0.5.2", features = ["web-axum"] }
sync_wrapper = "0.1"
